name: local_storage_todos_api
description: A Flutter implementation of the TodosApi that uses local storage.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  rxdart: ^0.28.0
  shared_preferences: ^2.2.3
  todos_api:
    path: ../todos_api

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  test_coverage_badge: ^0.2.0
  very_good_analysis: ^5.1.0
