include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - "lib/**.g.dart"
    - "lib/**.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    public_member_api_docs: false
