name: todos_api
description: The interface and models for an API providing access to todos.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  equatable: ^2.0.5
  faker: ^2.1.0
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  meta: ^1.15.0
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^5.1.0
