name: CI/CD

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        timeout-minutes: 1
      - name: Setup .env
        run: cp .env.example .env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
          pub-cache-key: "flutter-pub:os:-:channel:-:version:-:arch:-:hash:" # optional, change this to force refresh cache of dart pub get dependencies
          pub-cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:" # optional, change this to specify the cache path
        timeout-minutes: 5
      - name: Check version
        run: flutter --version
        timeout-minutes: 1
      - name: Install very good cli
        run: dart pub global activate very_good_cli
        timeout-minutes: 2
      - name: Install dependencies
        run: very_good packages get --recursive
        timeout-minutes: 4
      - name: Format
        run: dart format . --set-exit-if-changed
        timeout-minutes: 10
  test:
    runs-on: ubuntu-latest
    needs: [ format ]
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        timeout-minutes: 1
      - name: Setup .env
        run: cp .env.example .env
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
          cache: true
        timeout-minutes: 5
      - name: Check version
        run: flutter --version
        timeout-minutes: 1
      - name: Install very good cli
        run: dart pub global activate very_good_cli
        timeout-minutes: 2
      - name: Install dependencies
        run: very_good packages get --recursive
        timeout-minutes: 4
      - name: Testing
        run: very_good test --recursive
        timeout-minutes: 10
