name: Test Application

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        timeout-minutes: 1
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml # path to pubspec.yaml
        timeout-minutes: 5
      - name: Check version
        run: flutter --version
        timeout-minutes: 1
      - name: Install dependencies
        run: flutter pub get
        timeout-minutes: 10
      - name: Testing
        run: very_good test --recursive
        timeout-minutes: 10
